"""Initial schema, plus database-level protection of the audit trail.

Revision ID: 0001
Revises:
Create Date: 2026-09-25
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_head",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_seq", sa.Integer(), nullable=False),
        sa.Column("last_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("seq", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
        sa.UniqueConstraint("hash"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_entity", ["entity_type", "entity_id"], unique=False)

    op.create_table(
        "controls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "methodologies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
        sa.UniqueConstraint("key", "version"),
    )
    op.create_table(
        "risks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("next_review_due", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_hash"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("trials", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("engine_version", sa.String(length=16), nullable=False),
        sa.Column("methodology_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("inputs_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("result_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("computed_level", sa.String(length=32), nullable=False),
        sa.Column("current_ale", sa.Double(), nullable=False),
        sa.Column("override_level", sa.String(length=32), nullable=True),
        sa.Column("override_justification", sa.Text(), nullable=True),
        sa.Column("override_by", sa.String(length=64), nullable=True),
        sa.Column("override_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assessed_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_by", sa.String(length=64), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assessments", schema=None) as batch_op:
        batch_op.create_index("ix_assessments_risk_status", ["risk_id", "status"], unique=False)

    op.create_table(
        "risk_acceptances",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("accepted_level", sa.String(length=32), nullable=False),
        sa.Column("accepted_ale", sa.Double(), nullable=False),
        sa.Column("required_authority", sa.String(length=32), nullable=False),
        sa.Column("accepted_by", sa.String(length=64), nullable=False),
        sa.Column("accepted_role", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("conditions", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("closed_by", sa.String(length=64), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "treatment_approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("option_id", sa.String(length=64), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    _create_protection_triggers()


# Defence in depth: the application never updates or deletes audit entries, and never
# changes a finalised assessment. The database refuses it too, so a bug or a
# direct SQL session cannot silently rewrite history. (A DBA who drops the
# triggers can still tamper; the hash chain then makes that detectable.)
_FROZEN_ASSESSMENT_COLUMNS = (
    "inputs, inputs_fingerprint, result, result_fingerprint, computed_level, current_ale, "
    "override_level, override_justification, override_by, assessed_by, as_of, trials, seed"
)


def _create_protection_triggers() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        for event in ("UPDATE", "DELETE"):
            op.execute(
                f"CREATE TRIGGER audit_log_no_{event.lower()} BEFORE {event} ON audit_log "
                "BEGIN SELECT RAISE(ABORT, 'audit_log is append-only'); END;"
            )
        op.execute(
            f"CREATE TRIGGER assessment_final_immutable BEFORE UPDATE OF {_FROZEN_ASSESSMENT_COLUMNS} "
            "ON assessments WHEN OLD.status != 'draft' "
            "BEGIN SELECT RAISE(ABORT, 'finalised assessments are immutable'); END;"
        )
        op.execute(
            "CREATE TRIGGER assessment_no_delete BEFORE DELETE ON assessments WHEN OLD.status != 'draft' "
            "BEGIN SELECT RAISE(ABORT, 'finalised assessments cannot be deleted'); END;"
        )
    elif dialect == "postgresql":
        op.execute(
            "CREATE FUNCTION sextant_audit_append_only() RETURNS trigger AS $$ "
            "BEGIN RAISE EXCEPTION 'audit_log is append-only'; END; $$ LANGUAGE plpgsql;"
        )
        op.execute(
            "CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log "
            "FOR EACH ROW EXECUTE FUNCTION sextant_audit_append_only();"
        )
        op.execute(
            "CREATE FUNCTION sextant_assessment_immutable() RETURNS trigger AS $$ BEGIN "
            "IF OLD.status <> 'draft' AND (TG_OP = 'DELETE' OR "
            "(NEW.inputs::text, NEW.result::text, NEW.result_fingerprint, NEW.computed_level, "
            "NEW.override_level, NEW.assessed_by) IS DISTINCT FROM "
            "(OLD.inputs::text, OLD.result::text, OLD.result_fingerprint, OLD.computed_level, "
            "OLD.override_level, OLD.assessed_by)) "
            "THEN RAISE EXCEPTION 'finalised assessments are immutable'; END IF; "
            "IF TG_OP = 'DELETE' THEN RETURN OLD; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;"
        )
        op.execute(
            "CREATE TRIGGER assessment_immutable BEFORE UPDATE OR DELETE ON assessments "
            "FOR EACH ROW EXECUTE FUNCTION sextant_assessment_immutable();"
        )


def _drop_protection_triggers() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        for name in (
            "audit_log_no_update",
            "audit_log_no_delete",
            "assessment_final_immutable",
            "assessment_no_delete",
        ):
            op.execute(f"DROP TRIGGER IF EXISTS {name}")
    elif dialect == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
        op.execute("DROP TRIGGER IF EXISTS assessment_immutable ON assessments")
        op.execute("DROP FUNCTION IF EXISTS sextant_audit_append_only()")
        op.execute("DROP FUNCTION IF EXISTS sextant_assessment_immutable()")


def downgrade() -> None:
    _drop_protection_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("treatment_approvals")
    op.drop_table("risk_acceptances")
    with op.batch_alter_table("assessments", schema=None) as batch_op:
        batch_op.drop_index("ix_assessments_risk_status")

    op.drop_table("assessments")
    op.drop_table("users")
    op.drop_table("risks")
    op.drop_table("methodologies")
    op.drop_table("evidence")
    op.drop_table("controls")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_entity")

    op.drop_table("audit_log")
    op.drop_table("audit_head")
    op.drop_table("assets")
    # ### end Alembic commands ###
