"""Build src/sextant/compliance/catalogs/nist_csf_2_0.yaml from NIST's official OSCAL catalog.

Source: https://github.com/usnistgov/oscal-content  nist.gov/CSF/v2.0/json/NIST_CSF_v2.0_catalog.json
NIST CSF 2.0 is a work of the U.S. Government and is in the public domain.
Withdrawn (CSF 1.1) elements are excluded.

Usage: python scripts/build_csf_catalog.py path/to/NIST_CSF_v2.0_catalog.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import yaml

OUT = Path(__file__).resolve().parents[1] / "src/sextant/compliance/catalogs/nist_csf_2_0.yaml"


def props(node: dict[str, Any]) -> dict[str, str]:
    return {p["name"]: p.get("value", "") for p in node.get("props", [])}


def statement(node: dict[str, Any]) -> str:
    for part in node.get("parts", []):
        if part.get("name") in ("statement", "overview") and part.get("prose"):
            return " ".join(part["prose"].split())
    return ""


def main(src: str) -> None:
    catalog = json.loads(Path(src).read_text())["catalog"]
    groups: list[dict[str, str]] = []
    requirements: list[dict[str, str]] = []
    for function in catalog["groups"]:
        groups.append({"id": function["id"], "title": function["title"].title(), "parent": ""})
        for category in function.get("groups", []) + function.get("controls", []):
            if props(category).get("status") == "withdrawn":
                continue
            groups.append({"id": category["id"], "title": category["title"], "parent": function["id"]})
            for sub in category.get("controls", []):
                if props(sub).get("status") == "withdrawn":
                    continue
                requirements.append({"id": sub["id"], "title": statement(sub), "group": category["id"]})
    doc = {
        "id": "nist_csf_2_0",
        "name": "NIST Cybersecurity Framework 2.0",
        "version": "2.0",
        "publisher": "National Institute of Standards and Technology",
        "source": "NIST CSWP 29 via the official OSCAL catalog (usnistgov/oscal-content, "
        f"metadata version {catalog['metadata'].get('version')})",
        "license": "Public domain (work of the U.S. Government, 17 U.S.C. 105)",
        "text_policy": "verbatim",
        "kind": "outcome_framework",
        "groups": groups,
        "requirements": requirements,
    }
    OUT.write_text(
        "# Generated by scripts/build_csf_catalog.py; do not edit by hand.\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=120)
    )
    print(f"wrote {len(groups)} groups and {len(requirements)} subcategories to {OUT}")


if __name__ == "__main__":
    main(sys.argv[1])
